/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hafizramadhan_191011402923_projectakhir;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mdm
 */
public class AplikasiBukuTelepon extends javax.swing.JFrame {
    private Connection conn;
    private Statement stat;
    private ResultSet res;
    private String t;
    private DefaultTableModel dtm;
    /**
     * Creates new form InputDataBukuTeleponUTSHafizRamadhan
     * Hafiz Ramadhan
     * 191011402923
     */
    public AplikasiBukuTelepon() {
        initComponents();
        // status(); // tidak perlu di inisialisasi, karena sudah di set by model
        // rata kiri kanan
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation (
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2
        );
        koneksi();
        bersih();
        initDataTable();
    }
    
    private void koneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1/kontakhfzrmd", "root", "");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void bersih(){
        HafizRamadhan_NamaKontak.setText("");
        HafizRamadhan_NomorKontak.setText("");
        HafizRamadhan_AlamatKontak.setText("");
        HafizRamadhan_Status.setSelectedIndex(-1);
        HafizRamadhan_IDKontak.setText("");
    }
    
    private void status(){
        HafizRamadhan_Status.addItem("Keluarga");
        HafizRamadhan_Status.addItem("Teman");
        HafizRamadhan_Status.addItem("Kenalan");
        HafizRamadhan_Status.addItem("Rekan Kerja");
        HafizRamadhan_Status.setSelectedIndex(-1);
    }
    
    private void initDataTable(){
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("id");
        t.addColumn("Nama");
        t.addColumn("Nomor");
        t.addColumn("Alamat");
        t.addColumn("Status");
        
        TableDataKontak.setModel(t);
        try {
            res = conn.createStatement().executeQuery("SELECT * FROM data");
            while(res.next()){
                t.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("nomor"),
                    res.getString("alamat"),
                    res.getString("status")
                });
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelDataKontak = new javax.swing.JLabel();
        LabelInfoInputKontak = new javax.swing.JLabel();
        HafizRamadhan_NamaKontak = new javax.swing.JTextField();
        LabelNamaKontak = new javax.swing.JLabel();
        LabelNomorKontak = new javax.swing.JLabel();
        HafizRamadhan_NomorKontak = new javax.swing.JTextField();
        LabelAlamatKontak = new javax.swing.JLabel();
        HafizRamadhan_AlamatKontak = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        HafizRamadhan_Status = new javax.swing.JComboBox();
        HafizRamadhan_Simpan = new javax.swing.JButton();
        HafizRamadhan_Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDataKontak = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        LabelInfoDataKontak = new javax.swing.JLabel();
        HafizRamadhan_IDKontak = new javax.swing.JTextField();
        HafizRamadhan_Cari = new javax.swing.JButton();
        HafizRamadhan_Edit = new javax.swing.JButton();
        HafizRamadhan_Keluar = new javax.swing.JButton();
        HafizRamadhan_Refresh = new javax.swing.JButton();
        HafizRamadhan_Hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelDataKontak.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelDataKontak.setText("Data Kontak");

        LabelInfoInputKontak.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelInfoInputKontak.setText("Hafiz Ramadhan - 191011402923");

        HafizRamadhan_NamaKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_NamaKontakActionPerformed(evt);
            }
        });

        LabelNamaKontak.setText("Nama Kontak");

        LabelNomorKontak.setText("Nomor Kontak");

        HafizRamadhan_NomorKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_NomorKontakActionPerformed(evt);
            }
        });

        LabelAlamatKontak.setText("Alamat Kontak");

        HafizRamadhan_AlamatKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_AlamatKontakActionPerformed(evt);
            }
        });

        jLabel4.setText("Status");

        HafizRamadhan_Status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Keluarga", "Teman", "Kenalan", "Rekan Kerja" }));
        HafizRamadhan_Status.setSelectedIndex(-1);
        HafizRamadhan_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_StatusActionPerformed(evt);
            }
        });

        HafizRamadhan_Simpan.setText("Save");
        HafizRamadhan_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_SimpanActionPerformed(evt);
            }
        });

        HafizRamadhan_Clear.setText("Clear");
        HafizRamadhan_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_ClearActionPerformed(evt);
            }
        });

        TableDataKontak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableDataKontak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataKontakMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableDataKontak);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Input Kontak");

        LabelInfoDataKontak.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelInfoDataKontak.setText("Hafiz Ramadhan - 191011402923");

        HafizRamadhan_IDKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_IDKontakActionPerformed(evt);
            }
        });

        HafizRamadhan_Cari.setText("Search");
        HafizRamadhan_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_CariActionPerformed(evt);
            }
        });

        HafizRamadhan_Edit.setText("Edit");
        HafizRamadhan_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_EditActionPerformed(evt);
            }
        });

        HafizRamadhan_Keluar.setText("Exit");
        HafizRamadhan_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_KeluarActionPerformed(evt);
            }
        });

        HafizRamadhan_Refresh.setText("Refresh");
        HafizRamadhan_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_RefreshActionPerformed(evt);
            }
        });

        HafizRamadhan_Hapus.setText("Delete");
        HafizRamadhan_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_HapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNamaKontak)
                            .addComponent(LabelNomorKontak)
                            .addComponent(LabelAlamatKontak)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HafizRamadhan_Status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HafizRamadhan_NamaKontak)
                            .addComponent(HafizRamadhan_AlamatKontak)
                            .addComponent(HafizRamadhan_NomorKontak)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(HafizRamadhan_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HafizRamadhan_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(HafizRamadhan_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(LabelInfoInputKontak))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelInfoDataKontak, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelDataKontak, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(171, 171, 171))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HafizRamadhan_Hapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(HafizRamadhan_IDKontak, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HafizRamadhan_Cari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HafizRamadhan_Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HafizRamadhan_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LabelDataKontak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelInfoInputKontak)
                    .addComponent(LabelInfoDataKontak))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNamaKontak)
                            .addComponent(HafizRamadhan_NamaKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNomorKontak)
                            .addComponent(HafizRamadhan_NomorKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HafizRamadhan_AlamatKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAlamatKontak)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HafizRamadhan_Refresh)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(HafizRamadhan_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HafizRamadhan_Keluar)
                        .addComponent(HafizRamadhan_IDKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HafizRamadhan_Cari)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HafizRamadhan_Simpan)
                    .addComponent(HafizRamadhan_Hapus)
                    .addComponent(HafizRamadhan_Edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HafizRamadhan_Clear)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HafizRamadhan_NamaKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_NamaKontakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HafizRamadhan_NamaKontakActionPerformed

    private void HafizRamadhan_NomorKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_NomorKontakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HafizRamadhan_NomorKontakActionPerformed

    private void HafizRamadhan_AlamatKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_AlamatKontakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HafizRamadhan_AlamatKontakActionPerformed

    private void HafizRamadhan_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HafizRamadhan_StatusActionPerformed

    private void HafizRamadhan_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_SimpanActionPerformed
        // TODO add your handling code here:
        try {
            conn.createStatement().executeUpdate("insert into data (nama, nomor, alamat, status) values("
                + "'" + HafizRamadhan_NamaKontak.getText() + "',"
                + "'" + HafizRamadhan_NomorKontak.getText() + "',"
                + "'" + HafizRamadhan_AlamatKontak.getText() + "',"
                + "'" + HafizRamadhan_Status.getSelectedItem() + "')");
            bersih();
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan data!");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Kesalahan: " + e);
        }
    }//GEN-LAST:event_HafizRamadhan_SimpanActionPerformed

    private void HafizRamadhan_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_ClearActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_HafizRamadhan_ClearActionPerformed

    private void HafizRamadhan_IDKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_IDKontakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HafizRamadhan_IDKontakActionPerformed

    private void HafizRamadhan_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_EditActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah kamu yakin ingin mengupdate data ini ?", "Confirmation" , JOptionPane.YES_NO_OPTION);
        if (confirm == 0){
            PreparedStatement st;
            try {
                String sql = "UPDATE data SET nama = ?, nomor = ?, alamat = ?, status = ? WHERE id ='"+HafizRamadhan_IDKontak.getText()+"' ";
                st = conn.prepareStatement(sql);
                st.setString(1, HafizRamadhan_NamaKontak.getText());
                st.setString(2, HafizRamadhan_NomorKontak.getText());
                st.setString(3, HafizRamadhan_AlamatKontak.getText());
                st.setString(4, (String) HafizRamadhan_Status.getSelectedItem());
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
                initDataTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal diupdate, karena: " + ex);
            }
        }
    }//GEN-LAST:event_HafizRamadhan_EditActionPerformed

    private void HafizRamadhan_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_KeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_HafizRamadhan_KeluarActionPerformed

    private void HafizRamadhan_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_CariActionPerformed
        // TODO add your handling code here:
        try {
            res = conn.createStatement().executeQuery("SELECT * FROM data WHERE id = '"+HafizRamadhan_IDKontak.getText()+"'");
            while (res.next()){
                HafizRamadhan_NamaKontak.setText(res.getString("nama"));
                HafizRamadhan_NomorKontak.setText(res.getString("nomor"));
                HafizRamadhan_AlamatKontak.setText(res.getString("alamat"));
                HafizRamadhan_Status.setSelectedItem(res.getString("status"));
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_HafizRamadhan_CariActionPerformed

    private void HafizRamadhan_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_RefreshActionPerformed
        // TODO add your handling code here:
        initDataTable();
    }//GEN-LAST:event_HafizRamadhan_RefreshActionPerformed

    private void HafizRamadhan_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_HapusActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah kamu yakin ingin menghapus data ini ?", "Confirmation" , JOptionPane.YES_NO_OPTION);
        if (confirm == 0){
            PreparedStatement st;
            try {
                String sql = "DELETE FROM data WHERE id ='"+HafizRamadhan_IDKontak.getText()+"' ";
                st = conn.prepareStatement(sql);
                st.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil menghapus data");
                initDataTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal menghapus data, karena: " + ex);
            }
        }
    }//GEN-LAST:event_HafizRamadhan_HapusActionPerformed

    private void TableDataKontakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataKontakMouseClicked
        // TODO add your handling code here:
        int i = TableDataKontak.getSelectedRow();
        if (i == -1){
            return;
        }
        String Nama = (String)dtm.getValueAt(i,1);
        HafizRamadhan_NamaKontak.setText(Nama);
    }//GEN-LAST:event_TableDataKontakMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuTelepon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuTelepon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuTelepon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuTelepon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiBukuTelepon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HafizRamadhan_AlamatKontak;
    private javax.swing.JButton HafizRamadhan_Cari;
    private javax.swing.JButton HafizRamadhan_Clear;
    private javax.swing.JButton HafizRamadhan_Edit;
    private javax.swing.JButton HafizRamadhan_Hapus;
    private javax.swing.JTextField HafizRamadhan_IDKontak;
    private javax.swing.JButton HafizRamadhan_Keluar;
    private javax.swing.JTextField HafizRamadhan_NamaKontak;
    private javax.swing.JTextField HafizRamadhan_NomorKontak;
    private javax.swing.JButton HafizRamadhan_Refresh;
    private javax.swing.JButton HafizRamadhan_Simpan;
    private javax.swing.JComboBox HafizRamadhan_Status;
    private javax.swing.JLabel LabelAlamatKontak;
    private javax.swing.JLabel LabelDataKontak;
    private javax.swing.JLabel LabelInfoDataKontak;
    private javax.swing.JLabel LabelInfoInputKontak;
    private javax.swing.JLabel LabelNamaKontak;
    private javax.swing.JLabel LabelNomorKontak;
    private javax.swing.JTable TableDataKontak;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
