/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hafizramadhan_191011402923_projectakhir;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author mdm
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation (
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        HafizRamadhan_AngkaSatu = new javax.swing.JTextField();
        HafizRamadhan_AngkaDua = new javax.swing.JTextField();
        HafizRamadhan_Hasil = new javax.swing.JTextField();
        HafizRamadhan_Tambah = new javax.swing.JButton();
        HafizRamadhan_Kurang = new javax.swing.JButton();
        HafizRamadhan_Clear = new javax.swing.JButton();
        ButtonBackToHome = new javax.swing.JButton();
        HafizRamadhan_Kali = new javax.swing.JButton();
        HafizRamadhan_Bagi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HafizRamadhan_AngkaSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_AngkaSatuActionPerformed(evt);
            }
        });

        HafizRamadhan_AngkaDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_AngkaDuaActionPerformed(evt);
            }
        });

        HafizRamadhan_Tambah.setText("+");
        HafizRamadhan_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_TambahActionPerformed(evt);
            }
        });

        HafizRamadhan_Kurang.setText("-");
        HafizRamadhan_Kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_KurangActionPerformed(evt);
            }
        });

        HafizRamadhan_Clear.setText("Clear");
        HafizRamadhan_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_ClearActionPerformed(evt);
            }
        });

        ButtonBackToHome.setText("Home");
        ButtonBackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackToHomeActionPerformed(evt);
            }
        });

        HafizRamadhan_Kali.setText("x");
        HafizRamadhan_Kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_KaliActionPerformed(evt);
            }
        });

        HafizRamadhan_Bagi.setText("/");
        HafizRamadhan_Bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_BagiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("KALKULATOR SEDERHANA");

        jLabel5.setText("Hafiz Ramadhan - 191011402923");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HafizRamadhan_Clear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(HafizRamadhan_Tambah, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(HafizRamadhan_AngkaSatu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HafizRamadhan_AngkaDua)
                                    .addComponent(HafizRamadhan_Kurang, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonBackToHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(HafizRamadhan_Kali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HafizRamadhan_Bagi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(HafizRamadhan_Hasil, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addComponent(jLabel3))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HafizRamadhan_AngkaSatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HafizRamadhan_AngkaDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HafizRamadhan_Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HafizRamadhan_Tambah)
                    .addComponent(HafizRamadhan_Kurang)
                    .addComponent(HafizRamadhan_Kali)
                    .addComponent(HafizRamadhan_Bagi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HafizRamadhan_Clear)
                    .addComponent(ButtonBackToHome))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HafizRamadhan_AngkaSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_AngkaSatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HafizRamadhan_AngkaSatuActionPerformed

    private void HafizRamadhan_AngkaDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_AngkaDuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HafizRamadhan_AngkaDuaActionPerformed

    private void HafizRamadhan_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_TambahActionPerformed
        // TODO add your handling code here:
        int Angka_Satu = Integer.parseInt(HafizRamadhan_AngkaSatu.getText());
        int Angka_Dua = Integer.parseInt(HafizRamadhan_AngkaDua.getText());
        int Hasil_Operasi = Angka_Satu + Angka_Dua; // hasil dari perjumlahan
        // set text ke text field hasil -> Hasil_Operasi
        HafizRamadhan_Hasil.setText(Integer.toString(Hasil_Operasi));
    }//GEN-LAST:event_HafizRamadhan_TambahActionPerformed

    private void HafizRamadhan_KurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_KurangActionPerformed
        // TODO add your handling code here:
        int Angka_Satu = Integer.parseInt(HafizRamadhan_AngkaSatu.getText());
        int Angka_Dua = Integer.parseInt(HafizRamadhan_AngkaDua.getText());
        int Hasil_Operasi = Angka_Satu - Angka_Dua;
        
        HafizRamadhan_Hasil.setText(Integer.toString(Hasil_Operasi));
    }//GEN-LAST:event_HafizRamadhan_KurangActionPerformed

    private void HafizRamadhan_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_ClearActionPerformed
        // TODO add your handling code here:
        HafizRamadhan_AngkaSatu.setText(""); HafizRamadhan_AngkaSatu.requestFocus();
        HafizRamadhan_AngkaDua.setText("");
        HafizRamadhan_Hasil.setText("");
    }//GEN-LAST:event_HafizRamadhan_ClearActionPerformed

    private void ButtonBackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackToHomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true); dispose();
    }//GEN-LAST:event_ButtonBackToHomeActionPerformed

    private void HafizRamadhan_KaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_KaliActionPerformed
        // TODO add your handling code here:
        int Angka_Satu = Integer.parseInt(HafizRamadhan_AngkaSatu.getText());
        int Angka_Dua = Integer.parseInt(HafizRamadhan_AngkaDua.getText());
        int Hasil_Operasi = Angka_Satu * Angka_Dua;
        
        HafizRamadhan_Hasil.setText(Integer.toString(Hasil_Operasi));
    }//GEN-LAST:event_HafizRamadhan_KaliActionPerformed

    private void HafizRamadhan_BagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_BagiActionPerformed
        // TODO add your handling code here:
        int Angka_Satu = Integer.parseInt(HafizRamadhan_AngkaSatu.getText());
        int Angka_Dua = Integer.parseInt(HafizRamadhan_AngkaDua.getText());
        int Hasil_Operasi = Angka_Satu / Angka_Dua;
        
        HafizRamadhan_Hasil.setText(Integer.toString(Hasil_Operasi));
    }//GEN-LAST:event_HafizRamadhan_BagiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBackToHome;
    private javax.swing.JTextField HafizRamadhan_AngkaDua;
    private javax.swing.JTextField HafizRamadhan_AngkaSatu;
    private javax.swing.JButton HafizRamadhan_Bagi;
    private javax.swing.JButton HafizRamadhan_Clear;
    private javax.swing.JTextField HafizRamadhan_Hasil;
    private javax.swing.JButton HafizRamadhan_Kali;
    private javax.swing.JButton HafizRamadhan_Kurang;
    private javax.swing.JButton HafizRamadhan_Tambah;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
