/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hafizramadhan_191011402923_projectakhir;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mdm
 */
public class KelolaDataKelas extends javax.swing.JFrame {
    private Connection conn;
    private Statement stat;
    private ResultSet res;
    private String t;
    private DefaultTableModel dtm;
    private String TableKelas = "hafizramadhan_kelas";
    /**
     * Creates new form KelolaDataKelas
     */
    public KelolaDataKelas() {
        initComponents();
        koneksi();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation (
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2
        );
        initDataTable();
    }
    private void koneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1/inputdatasiswahafizramadhan", "root", "");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void initDataTable(){
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("id");
        t.addColumn("Nama");
        t.addColumn("Kode Kelas");
        t.addColumn("Kapasitas Kelas");
        
        HafizRamadhan_TableKelas.setModel(t);
        try {
            res = conn.createStatement().executeQuery("SELECT * FROM "+TableKelas+" ");
            while(res.next()){
                t.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("name"),
                    res.getString("code"),
                    res.getString("capacity"),
                });
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HafizRamadhan_Nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        HafizRamadhan_Kode = new javax.swing.JTextField();
        HafizRamadhan_Kapasitas = new javax.swing.JTextField();
        HafizRamadhan_Save = new javax.swing.JButton();
        HafizRamadhan_Clear = new javax.swing.JButton();
        HafizRamadhan_Home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HafizRamadhan_TableKelas = new javax.swing.JTable();
        HafizRamadhan_ID = new javax.swing.JTextField();
        HafizRamadhan_Searc = new javax.swing.JButton();
        HafizRamadhan_Refresh = new javax.swing.JButton();
        HafizRamadhan_Edit = new javax.swing.JButton();
        HafizRamadhan_Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Data Ruang Kelas");

        jLabel2.setText("Hafiz Ramadhan - 191011402923");

        jLabel3.setText("Nama");

        jLabel4.setText("Kode");

        jLabel5.setText("Kapasitas");

        HafizRamadhan_Save.setText("Save");
        HafizRamadhan_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_SaveActionPerformed(evt);
            }
        });

        HafizRamadhan_Clear.setText("Clear");
        HafizRamadhan_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_ClearActionPerformed(evt);
            }
        });

        HafizRamadhan_Home.setText("Home");
        HafizRamadhan_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_HomeActionPerformed(evt);
            }
        });

        HafizRamadhan_TableKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(HafizRamadhan_TableKelas);

        HafizRamadhan_Searc.setText("Search");
        HafizRamadhan_Searc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_SearcActionPerformed(evt);
            }
        });

        HafizRamadhan_Refresh.setText("Refresh");
        HafizRamadhan_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_RefreshActionPerformed(evt);
            }
        });

        HafizRamadhan_Edit.setText("Edit");
        HafizRamadhan_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_EditActionPerformed(evt);
            }
        });

        HafizRamadhan_Delete.setText("Delete");
        HafizRamadhan_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(HafizRamadhan_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HafizRamadhan_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(HafizRamadhan_Kode)
                                    .addComponent(HafizRamadhan_Kapasitas, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(HafizRamadhan_Nama)))
                            .addComponent(HafizRamadhan_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(HafizRamadhan_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HafizRamadhan_Searc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HafizRamadhan_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HafizRamadhan_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HafizRamadhan_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(318, 318, 318)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HafizRamadhan_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HafizRamadhan_Kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(HafizRamadhan_Kapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HafizRamadhan_Save)
                            .addComponent(HafizRamadhan_Clear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HafizRamadhan_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HafizRamadhan_Home))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HafizRamadhan_Searc)
                                .addComponent(HafizRamadhan_Refresh)
                                .addComponent(HafizRamadhan_Edit)
                                .addComponent(HafizRamadhan_Delete))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HafizRamadhan_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_HomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true); dispose();
    }//GEN-LAST:event_HafizRamadhan_HomeActionPerformed

    private void HafizRamadhan_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_ClearActionPerformed
        // TODO add your handling code here:
        HafizRamadhan_Nama.setText(""); HafizRamadhan_Nama.requestFocus();
        HafizRamadhan_Kode.setText("");
        HafizRamadhan_Kapasitas.setText("");
        HafizRamadhan_ID.setText("");
    }//GEN-LAST:event_HafizRamadhan_ClearActionPerformed

    private void HafizRamadhan_SearcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_SearcActionPerformed
        // TODO add your handling code here:
        try {
            res = conn.createStatement().executeQuery("SELECT * FROM "+TableKelas+" WHERE id = '"+HafizRamadhan_ID.getText()+"'");
            while (res.next()){
                HafizRamadhan_Nama.setText(res.getString("name"));
                HafizRamadhan_Kode.setText(res.getString("code"));
                HafizRamadhan_Kapasitas.setText(res.getString("capacity"));
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_HafizRamadhan_SearcActionPerformed

    private void HafizRamadhan_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_RefreshActionPerformed
        // TODO add your handling code here:
        initDataTable();
    }//GEN-LAST:event_HafizRamadhan_RefreshActionPerformed

    private void HafizRamadhan_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_SaveActionPerformed
        // TODO add your handling code here:
        String NamaLengkap = HafizRamadhan_Nama.getText();
        String Kode = HafizRamadhan_Kode.getText();
        String Kapasitas = HafizRamadhan_Kapasitas.getText();
        try {
            conn.createStatement().executeUpdate("insert into hafizramadhan_kelas (name, code, capacity) values("
                + "'" + NamaLengkap + "',"
                + "'" + Kode + "',"
                + "'" + Kapasitas + "')");
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan data!");
            initDataTable();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Kesalahan: " + e);
        }
    }//GEN-LAST:event_HafizRamadhan_SaveActionPerformed

    private void HafizRamadhan_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_EditActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah kamu yakin ingin mengupdate data ini ?", "Confirmation" , JOptionPane.YES_NO_OPTION);
        if (confirm == 0){
            PreparedStatement st;
            try {
                String sql = "UPDATE "+TableKelas+" SET name = ?, code = ?, capacity = ? WHERE id ='"+HafizRamadhan_ID.getText()+"' ";
                st = conn.prepareStatement(sql);
                st.setString(1, HafizRamadhan_Nama.getText());
                st.setString(2, HafizRamadhan_Kode.getText());
                st.setString(3, HafizRamadhan_Kapasitas.getText());
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
                initDataTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal diupdate, karena: " + ex);
            }
        }
    }//GEN-LAST:event_HafizRamadhan_EditActionPerformed

    private void HafizRamadhan_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_DeleteActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah kamu yakin ingin menghapus data ini ?", "Confirmation" , JOptionPane.YES_NO_OPTION);
        if (confirm == 0){
            PreparedStatement st;
            try {
                String sql = "DELETE FROM "+TableKelas+" WHERE id ='"+HafizRamadhan_ID.getText()+"' ";
                st = conn.prepareStatement(sql);
                st.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil menghapus data");
                initDataTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal menghapus data, karena: " + ex);
            }
        }
    }//GEN-LAST:event_HafizRamadhan_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaDataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaDataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaDataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaDataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaDataKelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HafizRamadhan_Clear;
    private javax.swing.JButton HafizRamadhan_Delete;
    private javax.swing.JButton HafizRamadhan_Edit;
    private javax.swing.JButton HafizRamadhan_Home;
    private javax.swing.JTextField HafizRamadhan_ID;
    private javax.swing.JTextField HafizRamadhan_Kapasitas;
    private javax.swing.JTextField HafizRamadhan_Kode;
    private javax.swing.JTextField HafizRamadhan_Nama;
    private javax.swing.JButton HafizRamadhan_Refresh;
    private javax.swing.JButton HafizRamadhan_Save;
    private javax.swing.JButton HafizRamadhan_Searc;
    private javax.swing.JTable HafizRamadhan_TableKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
