/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hafizramadhan_191011402923_projectakhir;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mdm
 */
public class Penilaian extends javax.swing.JFrame {
    private Connection conn;
    private Statement stat;
    private ResultSet res;
    private String t;
    private DefaultTableModel dtm;
    private String TablePenilaian = "hafizramadhan_penilaian_mahasiswa";
    /**
     * Creates new form Penilaian
     */
    public Penilaian() {
        initComponents();
        koneksi();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation (
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2
        );
        initDataTable();
    }
    private void koneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1/inputdatasiswahafizramadhan", "root", "");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void initDataTable(){
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("id");
        t.addColumn("Nama");
        t.addColumn("Nilai UTS");
        t.addColumn("Nilai Tugas Mandiri");
        t.addColumn("Nilai UAS");
        t.addColumn("Peringkat");
        
        HafizRamadhan_TablePenilaian.setModel(t);
        try {
            res = conn.createStatement().executeQuery("SELECT * FROM "+TablePenilaian+" ");
            while(res.next()){
                t.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("name"),
                    res.getString("uts"),
                    res.getString("tm"),
                    res.getString("uas"),
                    res.getString("grade"),
                });
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelNamaLengkap = new javax.swing.JLabel();
        HafizRamadhan_NamaLengkap = new javax.swing.JTextField();
        LabelUTS = new javax.swing.JLabel();
        HafizRamadhan_NilaiUTS = new javax.swing.JTextField();
        LabelNilaiTugasMandiri = new javax.swing.JLabel();
        HafizRamadhan_NilaiTugasMandiri = new javax.swing.JTextField();
        LabelNilaiTugasMandiri1 = new javax.swing.JLabel();
        HafizRamadhan_NilaiUAS = new javax.swing.JTextField();
        HafizRamadhan_Result = new javax.swing.JButton();
        HafizRamadhan_Clear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        HafizRamadhan_Save = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        HasilNamaLengkap = new javax.swing.JLabel();
        HasilNilaiRataRata = new javax.swing.JLabel();
        HasilGrade = new javax.swing.JLabel();
        HasilKeterangan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HafizRamadhan_TablePenilaian = new javax.swing.JTable();
        HafizRamadhan_ID = new javax.swing.JTextField();
        HafizRamadhan_Search = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        HafizRamadhan_Refresh = new javax.swing.JButton();
        HafizRamadhan_Edit = new javax.swing.JButton();
        HafizRamadhan_Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PENILAIAN MAHASISWA");

        LabelNamaLengkap.setText("Nama Lengkap");

        LabelUTS.setText("Nilai UTS");

        HafizRamadhan_NilaiUTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_NilaiUTSActionPerformed(evt);
            }
        });

        LabelNilaiTugasMandiri.setText("Nilai Tugas Mandiri");

        HafizRamadhan_NilaiTugasMandiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_NilaiTugasMandiriActionPerformed(evt);
            }
        });

        LabelNilaiTugasMandiri1.setText("Nilai UAS");

        HafizRamadhan_NilaiUAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_NilaiUASActionPerformed(evt);
            }
        });

        HafizRamadhan_Result.setText("Result");
        HafizRamadhan_Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_ResultActionPerformed(evt);
            }
        });

        HafizRamadhan_Clear.setText("Clear");
        HafizRamadhan_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_ClearActionPerformed(evt);
            }
        });

        jLabel3.setText("Hafiz Ramadhan - 191011402923");

        HafizRamadhan_Save.setText("Save");
        HafizRamadhan_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_SaveActionPerformed(evt);
            }
        });

        HasilNamaLengkap.setText("Nama Lengkap");

        HasilNilaiRataRata.setText("Nilai Rata-rata");

        HasilGrade.setText("Grade");

        HasilKeterangan.setText("Keterangan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HasilKeterangan)
                    .addComponent(HasilGrade)
                    .addComponent(HasilNilaiRataRata)
                    .addComponent(HasilNamaLengkap))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HasilNamaLengkap)
                .addGap(18, 18, 18)
                .addComponent(HasilNilaiRataRata)
                .addGap(18, 18, 18)
                .addComponent(HasilGrade)
                .addGap(18, 18, 18)
                .addComponent(HasilKeterangan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Hasil Perhitungan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelNilaiTugasMandiri1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HafizRamadhan_NilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelUTS)
                                    .addComponent(LabelNamaLengkap)
                                    .addComponent(LabelNilaiTugasMandiri))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(HafizRamadhan_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(HafizRamadhan_Clear)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(HafizRamadhan_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HafizRamadhan_NilaiTugasMandiri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HafizRamadhan_NilaiUTS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HafizRamadhan_NamaLengkap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel2)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HafizRamadhan_NamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNamaLengkap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HafizRamadhan_NilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelUTS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HafizRamadhan_NilaiTugasMandiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNilaiTugasMandiri))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HafizRamadhan_NilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNilaiTugasMandiri1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HafizRamadhan_Result)
                            .addComponent(HafizRamadhan_Clear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HafizRamadhan_Save)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        HafizRamadhan_TablePenilaian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(HafizRamadhan_TablePenilaian);

        HafizRamadhan_Search.setText("Search");
        HafizRamadhan_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_SearchActionPerformed(evt);
            }
        });

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        HafizRamadhan_Refresh.setText("Refresh");
        HafizRamadhan_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_RefreshActionPerformed(evt);
            }
        });

        HafizRamadhan_Edit.setText("Edit");
        HafizRamadhan_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_EditActionPerformed(evt);
            }
        });

        HafizRamadhan_Delete.setText("Delete");
        HafizRamadhan_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HafizRamadhan_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(HafizRamadhan_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(HafizRamadhan_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(HafizRamadhan_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(77, 77, 77)
                            .addComponent(HafizRamadhan_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(HafizRamadhan_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(HafizRamadhan_Refresh)
                    .addComponent(HafizRamadhan_Search)
                    .addComponent(HafizRamadhan_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HafizRamadhan_Edit)
                    .addComponent(HafizRamadhan_Delete))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HafizRamadhan_NilaiUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_NilaiUTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HafizRamadhan_NilaiUTSActionPerformed

    private void HafizRamadhan_NilaiTugasMandiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_NilaiTugasMandiriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HafizRamadhan_NilaiTugasMandiriActionPerformed

    private void HafizRamadhan_NilaiUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_NilaiUASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HafizRamadhan_NilaiUASActionPerformed

    private void HafizRamadhan_ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_ResultActionPerformed

        String Nama_Lengkap = HafizRamadhan_NamaLengkap.getText();
        Double Nilai_UTS = Double.parseDouble(HafizRamadhan_NilaiUTS.getText());
        Double Nilai_Tugas_Mandiri = Double.parseDouble(HafizRamadhan_NilaiTugasMandiri.getText());
        Double Nilai_UAS = Double.parseDouble(HafizRamadhan_NilaiUAS.getText());
        Double Nilai_Rata_Rata = Nilai_UTS + Nilai_Tugas_Mandiri + Nilai_UAS / 3;

        HasilNamaLengkap.setText("Nama Lengkap: " + Nama_Lengkap);
        HasilNilaiRataRata.setText("Nilai Rata-rata: " + Double.toString(Nilai_Rata_Rata));

        String Grade, Keterangan;
        if (Nilai_Rata_Rata >= 80){
            Grade = "A";
            Keterangan = "Selamat "+ Nama_Lengkap +", anda lulus dengan sangat baik!";
        }else if(Nilai_Rata_Rata >= 70){
            Grade = "B";
            Keterangan = "Selamat "+ Nama_Lengkap +", anda lulus dengan baik!";
        }else if(Nilai_Rata_Rata >= 60){
            Grade = "C";
            Keterangan = "Selamat "+ Nama_Lengkap +", anda lulus dengan cukup baik";
        }else if(Nilai_Rata_Rata >= 50){
            Grade = "D";
            Keterangan = "Maaf "+ Nama_Lengkap +", nilai anda belum memenuhi syarat kelulusan.";
        }else{
            Grade = "E";
            Keterangan = "Maaf "+ Nama_Lengkap +", anda tidak lulus dan harus mengulang";
        }
        HasilGrade.setText("Grade: " + Grade);
        HasilKeterangan.setText("Keterangan: " + Keterangan);
    }//GEN-LAST:event_HafizRamadhan_ResultActionPerformed

    private void HafizRamadhan_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_ClearActionPerformed
        HafizRamadhan_NamaLengkap.setText(""); HafizRamadhan_NamaLengkap.requestFocus();
        HafizRamadhan_NilaiUTS.setText("");
        HafizRamadhan_NilaiTugasMandiri.setText("");
        HafizRamadhan_NilaiUAS.setText("");
        HasilNamaLengkap.setText("Nama Lengkap: ");
        HasilNilaiRataRata.setText("Nilai Rata-rata: ");
        HasilGrade.setText("Grade: ");
        HasilKeterangan.setText("Keterangan: ");
    }//GEN-LAST:event_HafizRamadhan_ClearActionPerformed

    private void HafizRamadhan_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_SaveActionPerformed
        // TODO add your handling code here:
        String NamaLengkap = HafizRamadhan_NamaLengkap.getText();
        
        int UTS = Integer.parseInt(HafizRamadhan_NilaiUTS.getText());
        int TM = Integer.parseInt(HafizRamadhan_NilaiTugasMandiri.getText());
        int UAS = Integer.parseInt(HafizRamadhan_NilaiUAS.getText());
        
        Double Nilai_UTS = Double.parseDouble(HafizRamadhan_NilaiUTS.getText());
        Double Nilai_Tugas_Mandiri = Double.parseDouble(HafizRamadhan_NilaiTugasMandiri.getText());
        Double Nilai_UAS = Double.parseDouble(HafizRamadhan_NilaiUAS.getText());
        Double Nilai_Rata_Rata = Nilai_UTS + Nilai_Tugas_Mandiri + Nilai_UAS / 3;

        String Grade, Keterangan;
        if (Nilai_Rata_Rata >= 80){
            Grade = "A";
        }else if(Nilai_Rata_Rata >= 70){
            Grade = "B";
        }else if(Nilai_Rata_Rata >= 60){
            Grade = "C";
        }else if(Nilai_Rata_Rata >= 50){
            Grade = "D";
        }else{
            Grade = "E";
        }
        
        try {
            conn.createStatement().executeUpdate("insert into hafizramadhan_penilaian_mahasiswa (name, uts, tm, uas, grade) values("
                + "'" + NamaLengkap + "',"
                + "'" + UTS + "',"
                + "'" + TM + "',"
                + "'" + UAS + "',"
                + "'" + Grade + "')");
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan data!");
            initDataTable();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Kesalahan: " + e);
        }
        
    }//GEN-LAST:event_HafizRamadhan_SaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true); dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HafizRamadhan_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_RefreshActionPerformed
        // TODO add your handling code here:
        initDataTable();
    }//GEN-LAST:event_HafizRamadhan_RefreshActionPerformed

    private void HafizRamadhan_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_SearchActionPerformed
        // TODO add your handling code here:
        try {
            res = conn.createStatement().executeQuery("SELECT * FROM "+TablePenilaian+" WHERE id = '"+HafizRamadhan_ID.getText()+"'");
            while (res.next()){
                HafizRamadhan_NamaLengkap.setText(res.getString("name"));
                HafizRamadhan_NilaiUTS.setText(res.getString("uts"));
                HafizRamadhan_NilaiTugasMandiri.setText(res.getString("tm"));
                HafizRamadhan_NilaiUAS.setText(res.getString("uas"));
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_HafizRamadhan_SearchActionPerformed

    private void HafizRamadhan_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_EditActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah kamu yakin ingin mengupdate data ini ?", "Confirmation" , JOptionPane.YES_NO_OPTION);
        if (confirm == 0){
            Double Nilai_UTS = Double.parseDouble(HafizRamadhan_NilaiUTS.getText());
            Double Nilai_Tugas_Mandiri = Double.parseDouble(HafizRamadhan_NilaiTugasMandiri.getText());
            Double Nilai_UAS = Double.parseDouble(HafizRamadhan_NilaiUAS.getText());
            Double Nilai_Rata_Rata = Nilai_UTS + Nilai_Tugas_Mandiri + Nilai_UAS / 3;

            String Grade, Keterangan;
            if (Nilai_Rata_Rata >= 80){
                Grade = "A";
            }else if(Nilai_Rata_Rata >= 70){
                Grade = "B";
            }else if(Nilai_Rata_Rata >= 60){
                Grade = "C";
            }else if(Nilai_Rata_Rata >= 50){
                Grade = "D";
            }else{
                Grade = "E";
            }
            PreparedStatement st;
            try {
                String sql = "UPDATE "+TablePenilaian+" SET name = ?, uts = ?, tm = ?, uas = ?, grade = ? WHERE id ='"+HafizRamadhan_ID.getText()+"' ";
                st = conn.prepareStatement(sql);
                st.setString(1, HafizRamadhan_NamaLengkap.getText());
                st.setString(2, HafizRamadhan_NilaiUTS.getText());
                st.setString(3, HafizRamadhan_NilaiTugasMandiri.getText());
                st.setString(4, HafizRamadhan_NilaiUAS.getText());
                st.setString(5, Grade);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
                initDataTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal diupdate, karena: " + ex);
            }
        }
    }//GEN-LAST:event_HafizRamadhan_EditActionPerformed

    private void HafizRamadhan_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HafizRamadhan_DeleteActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah kamu yakin ingin menghapus data ini ?", "Confirmation" , JOptionPane.YES_NO_OPTION);
        if (confirm == 0){
            PreparedStatement st;
            try {
                String sql = "DELETE FROM "+TablePenilaian+" WHERE id ='"+HafizRamadhan_ID.getText()+"' ";
                st = conn.prepareStatement(sql);
                st.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil menghapus data");
                initDataTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal menghapus data, karena: " + ex);
            }
        }
    }//GEN-LAST:event_HafizRamadhan_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penilaian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HafizRamadhan_Clear;
    private javax.swing.JButton HafizRamadhan_Delete;
    private javax.swing.JButton HafizRamadhan_Edit;
    private javax.swing.JTextField HafizRamadhan_ID;
    private javax.swing.JTextField HafizRamadhan_NamaLengkap;
    private javax.swing.JTextField HafizRamadhan_NilaiTugasMandiri;
    private javax.swing.JTextField HafizRamadhan_NilaiUAS;
    private javax.swing.JTextField HafizRamadhan_NilaiUTS;
    private javax.swing.JButton HafizRamadhan_Refresh;
    private javax.swing.JButton HafizRamadhan_Result;
    private javax.swing.JButton HafizRamadhan_Save;
    private javax.swing.JButton HafizRamadhan_Search;
    private javax.swing.JTable HafizRamadhan_TablePenilaian;
    private javax.swing.JLabel HasilGrade;
    private javax.swing.JLabel HasilKeterangan;
    private javax.swing.JLabel HasilNamaLengkap;
    private javax.swing.JLabel HasilNilaiRataRata;
    private javax.swing.JLabel LabelNamaLengkap;
    private javax.swing.JLabel LabelNilaiTugasMandiri;
    private javax.swing.JLabel LabelNilaiTugasMandiri1;
    private javax.swing.JLabel LabelUTS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
